# Generated by Django 5.1.6 on 2025-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcomment',
            name='over_all_sentiment',
            field=models.CharField(choices=[('positive', '+ve'), ('negative', '-ve'), ('none', 'N/A')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchcomment',
            name='comment_type',
            field=models.CharField(choices=[('multiple_file', 'CSV File'), ('Youtube', 'YouTube')], max_length=20),
        ),
    ]
