# Generated by Django 5.1.6 on 2025-03-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_batchcomment_comment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='singlecomment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='batchcomment',
            name='over_all_sentiment',
            field=models.CharField(choices=[('positive', '+ve'), ('negative', '-ve'), ('none', 'N/A')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='CorrectedSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_comment', models.TextField()),
                ('predicted_sentiment', models.CharField(max_length=20)),
                ('corrected_sentiment', models.CharField(max_length=20)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
