# Generated by Django 5.1.6 on 2025-03-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_comment_is_updated_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsentiment',
            name='batch',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='analysis.batchcomment'),
            preserve_default=False,
        ),
    ]
