# Generated by Django 5.1.6 on 2025-03-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_correctedsentiment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsentiment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.batchcomment'),
        ),
    ]
