# Generated by Django 5.1.6 on 2025-03-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_correctedsentiment_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctedsentiment',
            name='batch',
        ),
        migrations.AddField(
            model_name='correctedsentiment',
            name='batch_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_comment', to='analysis.comment'),
        ),
        migrations.AddField(
            model_name='correctedsentiment',
            name='feedback_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctedsentiment',
            name='single_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_comment', to='analysis.singlecomment'),
        ),
        migrations.AlterField(
            model_name='batchcomment',
            name='over_all_sentiment',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='none', max_length=20),
        ),
    ]
