# Generated by Django 5.1.6 on 2025-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_remove_correctedsentiment_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctedsentiment',
            old_name='original_comment',
            new_name='comment',
        ),
    ]
